name: Test

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test'

    steps:
      - name: Get Code
        uses: actions/checkout@master

      - name: Install deps
        run: npm i

      - name: Test
        run: npm test


  publish:
    runs-on: ubuntu-latest
    name: Publish

    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
        - uses: actions/checkout@master

        - name: Install & build
          run: npm i && npm run build

        - run: npm run publish
          env:
            CF_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
