name: Test & Publish

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test'

    steps:
      - name: Get Code
        uses: actions/checkout@master

      - name: Install deps
        run: npm i

      - name: Test
        run: npm test


  publish:
    runs-on: ubuntu-latest
    name: Publish

    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
        - uses: actions/checkout@master

        - name: Install & build
          run: npm i && npm run build

        - name: Install wranger
          run: npm i -g @cloudflare/wrangler

        - run: wrangler publish -c ./wrangler.toml
          env:
            CF_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

        - name: Log to LogSnag
          uses: jsmrcaga/action-logsnag@v0.0.2
          with:
            token: ${{ secrets.LOGSNAG_TOKEN }}
            project: hooks
            channel: publish
            event: Published a new version (${{ github.run_number }})!
            icon: ⚙️
            notify: true
